language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install: pip install tox-travis coverage codacy-coverage

script: tox

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
